-- Complete PostgreSQL Script to Create 20 Blog Posts for Each User (160 total)
-- Run this script in PgAdmin after running the users and friendships script

-- Disable notices for cleaner output
SET client_min_messages = WARNING;

-- Create all blog posts in batches for better performance
INSERT INTO "BlogPosts" ("Id", "Title", "Content", "FeaturedImage", "Status", "AuthorId", "Tags", "CreatedAt", "UpdatedAt", "PublishedAt") VALUES 

-- Alice Johnson's Blog Posts (user_001) - 20 posts
(gen_random_uuid(), 'Getting Started with Web Development', 'Web development can seem overwhelming at first, but with the right approach, anyone can learn to build amazing websites. In this comprehensive guide, I''ll walk you through the essential technologies you need to know: HTML for structure, CSS for styling, and JavaScript for interactivity.', 'https://example.com/images/web-dev-basics.jpg', 1, 'user_001', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'The Power of Coffee in Programming', 'As developers, we have a special relationship with coffee. It''s not just a beverage; it''s fuel for creativity and problem-solving. In this post, I explore the science behind caffeine and productivity.', 'https://example.com/images/coffee.jpg', 1, 'user_001', '["tag3"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'React Hooks Deep Dive', 'React Hooks revolutionized how we write React components. In this detailed tutorial, we''ll explore useState, useEffect, useContext, and custom hooks with practical examples.', 'https://example.com/images/react-hooks.jpg', 1, 'user_001', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'CSS Grid Mastery', 'CSS Grid is a powerful layout system that makes creating complex, responsive layouts easier than ever. Learn grid properties and build real-world examples.', 'https://example.com/images/css-grid.jpg', 0, 'user_001', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'JavaScript ES6+ Features', 'Modern JavaScript offers many powerful features. Let''s explore arrow functions, destructuring, template literals, async/await, and the spread operator.', 'https://example.com/images/es6.jpg', 1, 'user_001', '["tag1"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Code Review Best Practices', 'Code reviews are essential for maintaining quality and fostering collaboration. Learn how to give and receive constructive feedback effectively.', 'https://example.com/images/code-review.jpg', 1, 'user_001', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Building REST APIs with Node.js', 'Creating robust APIs is crucial for modern applications. This guide covers designing endpoints, authentication, error handling, and testing.', 'https://example.com/images/nodejs-api.jpg', 0, 'user_001', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Database Design Principles', 'Good database design is the foundation of successful applications. Learn normalization, indexing, relationships, and performance optimization.', 'https://example.com/images/database.jpg', 1, 'user_001', '["tag2"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Frontend Performance Optimization', 'Website performance impacts user experience and SEO. Learn lazy loading, code splitting, image optimization, and caching strategies.', 'https://example.com/images/performance.jpg', 1, 'user_001', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Git Workflow Mastery', 'Master advanced Git techniques: interactive rebasing, cherry-picking, hooks, and effective branching strategies for solo and team development.', 'https://example.com/images/git.jpg', 0, 'user_001', '["tag3"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'TypeScript for JavaScript Developers', 'Making the transition from JavaScript to TypeScript improves code quality. Learn type annotations, interfaces, generics, and migration strategies.', 'https://example.com/images/typescript.jpg', 1, 'user_001', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Async Programming Fundamentals', 'Master asynchronous JavaScript: callbacks, promises, async/await, event loops, and common patterns for responsive applications.', 'https://example.com/images/async.jpg', 1, 'user_001', '["tag1", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'CSS Animations Guide', 'Bring websites to life with smooth animations. Learn keyframes, timing functions, and performance considerations for 60fps animations.', 'https://example.com/images/animations.jpg', 0, 'user_001', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Testing Web Applications', 'Comprehensive testing ensures reliable applications. Explore unit testing, integration testing, and end-to-end testing strategies.', 'https://example.com/images/testing.jpg', 1, 'user_001', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Progressive Web Apps', 'PWAs combine web and mobile app benefits. Learn service workers, push notifications, and offline functionality implementation.', 'https://example.com/images/pwa.jpg', 1, 'user_001', '["tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Debugging Like a Pro', 'Effective debugging saves hours of frustration. Master browser dev tools, Node.js debugging, and systematic troubleshooting approaches.', 'https://example.com/images/debugging.jpg', 0, 'user_001', '["tag1", "tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Web Security Essentials', 'Security should be built-in from the start. Learn about XSS, CSRF, SQL injection prevention, and authentication strategies.', 'https://example.com/images/security.jpg', 1, 'user_001', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Scalable Frontend Architecture', 'Structure large applications for maintainability. Explore component patterns, state management, and code organization strategies.', 'https://example.com/images/architecture.jpg', 1, 'user_001', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Developer Mindset and Growth', 'Success requires more than technical skills. Discuss problem-solving, continuous learning, and dealing with imposter syndrome.', 'https://example.com/images/mindset.jpg', 0, 'user_001', '["tag3"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'My Development Setup 2024', 'Share my current development environment: hardware, editor, extensions, terminal setup, and productivity tools for different budgets.', 'https://example.com/images/setup.jpg', 1, 'user_001', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Bob Smith's Blog Posts (user_002) - 20 posts  
(gen_random_uuid(), 'Open Source Contribution Guide', 'Contributing to open source projects is rewarding and educational. Learn how to find projects, understand guidelines, and make impactful contributions.', 'https://example.com/images/opensource.jpg', 1, 'user_002', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Full-Stack MEAN Development', 'Build complete web applications with MongoDB, Express.js, Angular, and Node.js. Master the entire JavaScript stack.', 'https://example.com/images/mean.jpg', 1, 'user_002', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Docker for Development', 'Containerization simplifies development and deployment. Learn Docker fundamentals, compose, and best practices for dev workflows.', 'https://example.com/images/docker.jpg', 1, 'user_002', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'GraphQL API Development', 'GraphQL provides flexible, efficient APIs. Master schema design, resolvers, queries, mutations, and performance optimization.', 'https://example.com/images/graphql.jpg', 0, 'user_002', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Microservices Architecture', 'Design scalable systems with microservices. Learn service decomposition, communication patterns, and deployment strategies.', 'https://example.com/images/microservices.jpg', 1, 'user_002', '["tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'CI/CD Pipeline Setup', 'Automate your deployment process. Build reliable pipelines with GitHub Actions, testing integration, and deployment strategies.', 'https://example.com/images/cicd.jpg', 1, 'user_002', '["tag3"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Database Migration Strategies', 'Safely evolve your database schema. Learn versioning, zero-downtime deployments, and rollback procedures.', 'https://example.com/images/migration.jpg', 0, 'user_002', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'API Documentation Best Practices', 'Create documentation developers love. Use OpenAPI, interactive docs, and clear examples to accelerate adoption.', 'https://example.com/images/api-docs.jpg', 1, 'user_002', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'System Monitoring and Observability', 'Understand production behavior through metrics, logging, and tracing. Implement comprehensive observability strategies.', 'https://example.com/images/observability.jpg', 1, 'user_002', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Event-Driven Architecture', 'Build loosely coupled systems with events. Learn event sourcing, CQRS, message queues, and streaming architectures.', 'https://example.com/images/events.jpg', 0, 'user_002', '["tag2"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Kubernetes Deployment Guide', 'Orchestrate containers at scale. Master pods, services, deployments, and production-ready Kubernetes configurations.', 'https://example.com/images/k8s.jpg', 1, 'user_002', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Real-time WebSocket Applications', 'Enable bidirectional communication. Build chat apps, live updates, and collaborative features with WebSockets.', 'https://example.com/images/websockets.jpg', 1, 'user_002', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Caching Strategies Guide', 'Improve performance with strategic caching. Learn browser, CDN, Redis, and application-level caching techniques.', 'https://example.com/images/caching.jpg', 0, 'user_002', '["tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Building Resilient Systems', 'Design for failure with circuit breakers, retries, timeouts, and graceful degradation patterns.', 'https://example.com/images/resilience.jpg', 1, 'user_002', '["tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Load Balancing Essentials', 'Distribute traffic effectively. Learn algorithms, health checks, session affinity, and load balancer configuration.', 'https://example.com/images/loadbalancing.jpg', 1, 'user_002', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Message Queues and Processing', 'Implement asynchronous processing with RabbitMQ, Kafka, and background job systems for scalable applications.', 'https://example.com/images/queues.jpg', 0, 'user_002', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Infrastructure as Code', 'Manage infrastructure through code. Master Terraform, CloudFormation, and configuration management tools.', 'https://example.com/images/iac.jpg', 1, 'user_002', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Building Developer Tools', 'Create tools that developers love. Design CLI utilities, editor extensions, and debugging tools with great UX.', 'https://example.com/images/devtools.jpg', 1, 'user_002', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Open Source Project Management', 'Successfully manage open source communities. Learn governance, contributor onboarding, and sustainable development.', 'https://example.com/images/oss-mgmt.jpg', 0, 'user_002', '["tag3"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Web Development Evolution', 'Reflect on how web development has changed. From jQuery to modern frameworks, JAMstack, and future trends.', 'https://example.com/images/evolution.jpg', 1, 'user_002', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Carol Davis's Blog Posts (user_003) - 20 posts
(gen_random_uuid(), 'UX Design Principles for Developers', 'Bridge the gap between design and development. Learn user-centered design, usability heuristics, and creating delightful experiences.', 'https://example.com/images/ux-principles.jpg', 1, 'user_003', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Creating Beautiful User Interfaces', 'Master UI design fundamentals: color theory, typography, spacing, visual hierarchy, and modern design trends.', 'https://example.com/images/beautiful-ui.jpg', 1, 'user_003', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Design Systems at Scale', 'Build consistent experiences with design systems. Learn component libraries, design tokens, and team collaboration.', 'https://example.com/images/design-systems.jpg', 1, 'user_003', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'User Research Methods', 'Understand your users through research. Master interviews, surveys, usability testing, and analytics interpretation.', 'https://example.com/images/user-research.jpg', 0, 'user_003', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Accessibility in Design', 'Design for everyone. Implement WCAG guidelines, screen reader support, keyboard navigation, and inclusive design patterns.', 'https://example.com/images/accessibility.jpg', 1, 'user_003', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Mobile-First Design Strategy', 'Prioritize mobile experiences. Learn responsive design, touch interactions, and progressive enhancement techniques.', 'https://example.com/images/mobile-first.jpg', 1, 'user_003', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Prototyping Tools and Techniques', 'Validate ideas before development. Compare sketching, wireframing, and interactive prototyping tools and methods.', 'https://example.com/images/prototyping.jpg', 0, 'user_003', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Color Psychology in UI Design', 'Harness the power of color. Learn color theory, cultural considerations, brand alignment, and emotional impact.', 'https://example.com/images/color-psychology.jpg', 1, 'user_003', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Typography for Digital Interfaces', 'Make text beautiful and readable. Master font selection, sizing, spacing, hierarchy, and web font optimization.', 'https://example.com/images/typography.jpg', 1, 'user_003', '["tag4"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Information Architecture Best Practices', 'Organize content effectively. Learn site mapping, card sorting, navigation design, and user flow optimization.', 'https://example.com/images/ia.jpg', 0, 'user_003', '["tag1", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Animation in User Interfaces', 'Enhance UX with thoughtful animation. Learn timing, easing, feedback animations, and performance considerations.', 'https://example.com/images/ui-animation.jpg', 1, 'user_003', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Designing for Global Audiences', 'Create culturally-aware designs. Consider reading patterns, color meanings, imagery, and localization needs.', 'https://example.com/images/global-design.jpg', 1, 'user_003', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'User Testing Strategies', 'Validate designs with real users. Plan tests, recruit participants, conduct sessions, and analyze findings.', 'https://example.com/images/user-testing.jpg', 0, 'user_003', '["tag3"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Conversion Rate Optimization', 'Design for conversions. Optimize landing pages, forms, CTAs, and use psychological triggers effectively.', 'https://example.com/images/cro.jpg', 1, 'user_003', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Design-Development Collaboration', 'Bridge the design-dev gap. Improve handoffs, documentation, and communication for better team outcomes.', 'https://example.com/images/collaboration.jpg', 1, 'user_003', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Micro-interactions and Feedback', 'Perfect the details that matter. Design hover states, loading indicators, form validation, and subtle animations.', 'https://example.com/images/microinteractions.jpg', 0, 'user_003', '["tag4"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Dark Mode Design Guide', 'Design effective dark themes. Learn color adaptation, accessibility, user preferences, and implementation strategies.', 'https://example.com/images/dark-mode.jpg', 1, 'user_003', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Voice Interface Design', 'Design for voice interactions. Learn conversation design, error handling, accessibility, and natural language patterns.', 'https://example.com/images/voice-ui.jpg', 1, 'user_003', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Design Trends vs Timeless Principles', 'Balance trends with fundamentals. Know when to follow trends and when to stick with proven design principles.', 'https://example.com/images/trends.jpg', 0, 'user_003', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Building a Design Portfolio', 'Showcase your design thinking. Structure portfolios, write case studies, and present work that attracts opportunities.', 'https://example.com/images/portfolio.jpg', 1, 'user_003', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- David Wilson's Blog Posts (user_004) - 20 posts
(gen_random_uuid(), 'DevOps Culture Transformation', 'Transform your organization with DevOps. Break down silos, foster collaboration, and implement cultural changes for success.', 'https://example.com/images/devops-culture.jpg', 1, 'user_004', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Infrastructure as Code with Terraform', 'Automate infrastructure provisioning. Master Terraform modules, state management, and multi-cloud deployments.', 'https://example.com/images/terraform.jpg', 1, 'user_004', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Kubernetes Production Deployment', 'Deploy applications to Kubernetes at scale. Learn cluster management, networking, storage, and security best practices.', 'https://example.com/images/k8s-prod.jpg', 1, 'user_004', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Monitoring and Alerting Systems', 'Build comprehensive observability. Implement Prometheus, Grafana, alerting rules, and incident response workflows.', 'https://example.com/images/monitoring.jpg', 0, 'user_004', '["tag3"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Cloud Security Architecture', 'Secure cloud workloads effectively. Implement zero-trust, identity management, encryption, and compliance frameworks.', 'https://example.com/images/cloud-security.jpg', 1, 'user_004', '["tag1", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'GitOps Deployment Strategies', 'Implement GitOps for reliable deployments. Use ArgoCD, Flux, and Git-based configuration management workflows.', 'https://example.com/images/gitops.jpg', 1, 'user_004', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Database Administration in Cloud', 'Manage cloud databases effectively. Learn RDS, backup strategies, performance tuning, and cost optimization.', 'https://example.com/images/cloud-db.jpg', 0, 'user_004', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Automation Scripts for DevOps', 'Eliminate manual work with automation. Build shell scripts, Python tools, and custom automation solutions.', 'https://example.com/images/automation.jpg', 1, 'user_004', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Site Reliability Engineering', 'Apply SRE principles for reliable systems. Implement SLIs, SLOs, error budgets, and incident management.', 'https://example.com/images/sre.jpg', 1, 'user_004', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Performance Optimization Techniques', 'Optimize system performance systematically. Monitor bottlenecks, implement caching, and scale infrastructure effectively.', 'https://example.com/images/performance.jpg', 0, 'user_004', '["tag2"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Disaster Recovery Planning', 'Prepare for disasters before they happen. Design backup strategies, recovery procedures, and business continuity plans.', 'https://example.com/images/disaster-recovery.jpg', 1, 'user_004', '["tag3"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Multi-Cloud Strategy', 'Leverage multiple cloud providers. Design portable architectures, manage costs, and avoid vendor lock-in.', 'https://example.com/images/multicloud.jpg', 1, 'user_004', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Cloud Cost Optimization', 'Control cloud spending effectively. Implement FinOps practices, reserved instances, spot instances, and cost monitoring.', 'https://example.com/images/cost-optimization.jpg', 0, 'user_004', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Zero Trust Security Model', 'Implement zero trust architecture. Design identity-based access, network segmentation, and continuous verification.', 'https://example.com/images/zero-trust.jpg', 1, 'user_004', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Configuration Management at Scale', 'Manage configuration across infrastructure. Use Ansible, Puppet, Chef, and handle configuration drift effectively.', 'https://example.com/images/config-mgmt.jpg', 1, 'user_004', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Incident Response Procedures', 'Handle incidents effectively. Build response procedures, communication plans, and post-incident learning processes.', 'https://example.com/images/incident-response.jpg', 0, 'user_004', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'DevOps Metrics and KPIs', 'Measure DevOps success with data. Track deployment frequency, lead time, failure rate, and business impact metrics.', 'https://example.com/images/devops-metrics.jpg', 1, 'user_004', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Container Security Best Practices', 'Secure containerized applications. Implement image security, runtime protection, and compliance scanning throughout lifecycle.', 'https://example.com/images/container-security.jpg', 1, 'user_004', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Edge Computing Strategies', 'Deploy applications at the edge. Implement CDN strategies, edge caching, and distributed application architectures.', 'https://example.com/images/edge-computing.jpg', 0, 'user_004', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Future of Infrastructure Technology', 'Explore emerging infrastructure trends. Discuss serverless, WebAssembly, quantum computing, and preparing for change.', 'https://example.com/images/future-infra.jpg', 1, 'user_004', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Eva Martinez's Blog Posts (user_005) - 20 posts
(gen_random_uuid(), 'Machine Learning Fundamentals', 'Start your ML journey. Learn supervised/unsupervised learning, algorithms, model evaluation, and practical applications.', 'https://example.com/images/ml-basics.jpg', 1, 'user_005', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Data Visualization Mastery', 'Tell stories with data. Master chart selection, color usage, interactive visualizations, and effective data communication.', 'https://example.com/images/dataviz.jpg', 1, 'user_005', '["tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Python for Data Science', 'Master Python''s data ecosystem. Learn NumPy, Pandas, Matplotlib, Scikit-learn, and Jupyter notebook workflows.', 'https://example.com/images/python-ds.jpg', 0, 'user_005', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '17 days', NULL),
(gen_random_uuid(), 'Deep Learning with Neural Networks', 'Understand neural network fundamentals. Learn neurons, layers, backpropagation, and build networks from scratch.', 'https://example.com/images/neural-nets.jpg', 1, 'user_005', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
(gen_random_uuid(), 'Big Data Processing with Spark', 'Handle large datasets efficiently. Master Apache Spark, RDDs, DataFrames, and distributed computing concepts.', 'https://example.com/images/spark.jpg', 1, 'user_005', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Data Engineering Pipelines', 'Build robust data pipelines. Learn ETL processes, data quality, scheduling, and pipeline monitoring strategies.', 'https://example.com/images/data-pipelines.jpg', 1, 'user_005', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Statistical Analysis for Data Science', 'Apply statistics to data problems. Learn hypothesis testing, confidence intervals, regression, and statistical modeling.', 'https://example.com/images/statistics.jpg', 0, 'user_005', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Feature Engineering Techniques', 'Transform raw data into ML-ready features. Learn encoding, scaling, selection, and domain-specific feature creation.', 'https://example.com/images/feature-engineering.jpg', 1, 'user_005', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Model Deployment and MLOps', 'Deploy ML models to production. Learn containerization, API development, monitoring, and MLOps best practices.', 'https://example.com/images/mlops.jpg', 1, 'user_005', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Time Series Analysis', 'Analyze temporal data patterns. Learn forecasting, seasonality detection, ARIMA models, and trend analysis techniques.', 'https://example.com/images/timeseries.jpg', 0, 'user_005', '["tag2"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Natural Language Processing', 'Process and understand text data. Learn tokenization, sentiment analysis, named entity recognition, and transformer models.', 'https://example.com/images/nlp.jpg', 1, 'user_005', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Computer Vision Applications', 'Build systems that see. Learn image processing, object detection, classification, and convolutional neural networks.', 'https://example.com/images/computer-vision.jpg', 1, 'user_005', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'A/B Testing for Data Scientists', 'Design and analyze experiments. Learn test design, statistical significance, power analysis, and result interpretation.', 'https://example.com/images/ab-testing.jpg', 0, 'user_005', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Database Design for Analytics', 'Optimize databases for analysis. Learn dimensional modeling, data warehousing, and analytics-optimized schemas.', 'https://example.com/images/analytics-db.jpg', 1, 'user_005', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Ethics in AI and Machine Learning', 'Build responsible AI systems. Address bias, fairness, transparency, privacy, and ethical considerations in ML.', 'https://example.com/images/ai-ethics.jpg', 1, 'user_005', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Data Quality and Validation', 'Ensure data reliability. Implement validation rules, quality metrics, profiling, and automated quality monitoring.', 'https://example.com/images/data-quality.jpg', 0, 'user_005', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Recommendation Systems', 'Build personalized recommendation engines. Learn collaborative filtering, content-based filtering, and hybrid approaches.', 'https://example.com/images/recommendations.jpg', 1, 'user_005', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Data Science Team Management', 'Lead successful data science teams. Learn project management, stakeholder communication, and technical leadership.', 'https://example.com/images/ds-management.jpg', 1, 'user_005', '["tag3"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Real-time Analytics Systems', 'Process streaming data in real-time. Learn Kafka, streaming analytics, low-latency processing, and event-driven architectures.', 'https://example.com/images/realtime-analytics.jpg', 0, 'user_005', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Career Path in Data Science', 'Navigate the data science career landscape. Explore specializations, skill development, portfolio building, and industry trends.', 'https://example.com/images/ds-career.jpg', 1, 'user_005', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Frank Thompson's Blog Posts (user_006) - 20 posts
(gen_random_uuid(), 'React Native vs Flutter Comparison', 'Choose the right cross-platform framework. Compare performance, development experience, and ecosystem maturity.', 'https://example.com/images/rn-flutter.jpg', 1, 'user_006', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Mobile App Performance Optimization', 'Build fast, responsive mobile apps. Learn optimization techniques, memory management, and performance monitoring.', 'https://example.com/images/mobile-performance.jpg', 1, 'user_006', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Native iOS Development with Swift', 'Master iOS development fundamentals. Learn Swift, UIKit, SwiftUI, and Apple''s development ecosystem.', 'https://example.com/images/ios-swift.jpg', 1, 'user_006', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Android Development with Kotlin', 'Build Android apps with modern Kotlin. Learn Android SDK, Jetpack Compose, and Google''s development tools.', 'https://example.com/images/android-kotlin.jpg', 0, 'user_006', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Mobile UI/UX Design Patterns', 'Create intuitive mobile interfaces. Learn platform conventions, touch interactions, and mobile-specific design patterns.', 'https://example.com/images/mobile-ux.jpg', 1, 'user_006', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'App Store Optimization Guide', 'Maximize app discoverability. Learn ASO strategies, keyword optimization, and conversion rate improvement techniques.', 'https://example.com/images/aso.jpg', 1, 'user_006', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Mobile App Security Best Practices', 'Secure mobile applications effectively. Implement encryption, secure storage, authentication, and vulnerability prevention.', 'https://example.com/images/mobile-security.jpg', 0, 'user_006', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Progressive Web Apps for Mobile', 'Build app-like web experiences. Learn service workers, offline functionality, and mobile PWA optimization.', 'https://example.com/images/pwa-mobile.jpg', 1, 'user_006', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Mobile App Testing Strategies', 'Ensure app quality across devices. Learn unit testing, UI testing, device testing, and automated testing frameworks.', 'https://example.com/images/mobile-testing.jpg', 1, 'user_006', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Mobile Analytics and Monitoring', 'Track app performance and user behavior. Implement crash reporting, user analytics, and performance monitoring.', 'https://example.com/images/mobile-analytics.jpg', 0, 'user_006', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Cross-Platform Development Strategies', 'Choose the right cross-platform approach. Compare frameworks, evaluate trade-offs, and make informed decisions.', 'https://example.com/images/crossplatform.jpg', 1, 'user_006', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Mobile Backend as a Service', 'Accelerate development with BaaS. Learn Firebase, AWS Amplify, and backend service integration strategies.', 'https://example.com/images/mobile-baas.jpg', 1, 'user_006', '["tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Offline-First Mobile Applications', 'Build apps that work without internet. Implement offline data sync, conflict resolution, and network resilience.', 'https://example.com/images/offline-mobile.jpg', 0, 'user_006', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Mobile Development DevOps', 'Automate mobile app delivery. Learn CI/CD for mobile, automated testing, and deployment pipeline optimization.', 'https://example.com/images/mobile-devops.jpg', 1, 'user_006', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Monetization Strategies for Mobile Apps', 'Generate revenue from mobile apps. Learn freemium models, in-app purchases, subscriptions, and ad integration.', 'https://example.com/images/mobile-monetization.jpg', 1, 'user_006', '["tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Mobile Accessibility Implementation', 'Make apps accessible to everyone. Implement screen reader support, voice control, and inclusive design patterns.', 'https://example.com/images/mobile-accessibility.jpg', 0, 'user_006', '["tag1", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Flutter Widget Deep Dive', 'Master Flutter''s widget system. Learn custom widgets, state management, and advanced Flutter development techniques.', 'https://example.com/images/flutter-widgets.jpg', 1, 'user_006', '["tag1", "tag2"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Mobile App Launch Strategies', 'Successfully launch mobile applications. Learn pre-launch preparation, marketing strategies, and launch optimization.', 'https://example.com/images/app-launch.jpg', 1, 'user_006', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'AR/VR in Mobile Development', 'Integrate augmented and virtual reality. Learn ARKit, ARCore, and building immersive mobile experiences.', 'https://example.com/images/mobile-ar.jpg', 0, 'user_006', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Future of Mobile Development', 'Explore emerging mobile technologies. Discuss 5G, edge computing, AI integration, and next-generation mobile experiences.', 'https://example.com/images/mobile-future.jpg', 1, 'user_006', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Grace Lee's Blog Posts (user_007) - 20 posts
(gen_random_uuid(), 'Product Management for Tech Teams', 'Bridge business and engineering. Learn requirement gathering, stakeholder management, and technical product strategy.', 'https://example.com/images/pm-tech.jpg', 1, 'user_007', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Agile Product Development', 'Execute agile product strategies. Learn sprint planning, backlog management, and iterative development processes.', 'https://example.com/images/agile-product.jpg', 1, 'user_007', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'User Story Writing Best Practices', 'Write effective user stories. Learn story formats, acceptance criteria, and stakeholder communication techniques.', 'https://example.com/images/user-stories.jpg', 1, 'user_007', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Product Roadmap Planning', 'Create strategic product roadmaps. Learn prioritization frameworks, timeline planning, and roadmap communication.', 'https://example.com/images/roadmap.jpg', 0, 'user_007', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Data-Driven Product Decisions', 'Use data to guide product strategy. Learn analytics interpretation, A/B testing, and metrics-driven development.', 'https://example.com/images/data-product.jpg', 1, 'user_007', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Stakeholder Management Strategies', 'Manage diverse stakeholder needs. Learn communication, expectation setting, and conflict resolution techniques.', 'https://example.com/images/stakeholders.jpg', 1, 'user_007', '["tag3"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Product Launch Execution', 'Execute successful product launches. Learn go-to-market strategies, launch planning, and post-launch optimization.', 'https://example.com/images/product-launch.jpg', 0, 'user_007', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Competitive Analysis Framework', 'Analyze competitive landscape effectively. Learn analysis techniques, positioning strategies, and differentiation.', 'https://example.com/images/competitive-analysis.jpg', 1, 'user_007', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Customer Discovery Methods', 'Understand customer needs deeply. Learn interview techniques, survey design, and customer research methodologies.', 'https://example.com/images/customer-discovery.jpg', 1, 'user_007', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Product Metrics and KPIs', 'Measure product success effectively. Learn key metrics, dashboard design, and performance tracking strategies.', 'https://example.com/images/product-metrics.jpg', 0, 'user_007', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Feature Prioritization Frameworks', 'Prioritize features systematically. Learn RICE, MoSCoW, Kano model, and other prioritization methodologies.', 'https://example.com/images/prioritization.jpg', 1, 'user_007', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Product Team Collaboration', 'Foster effective team collaboration. Learn cross-functional teamwork, communication, and alignment strategies.', 'https://example.com/images/team-collaboration.jpg', 1, 'user_007', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'B2B Product Management', 'Manage business-to-business products. Learn enterprise sales cycles, stakeholder complexity, and B2B strategies.', 'https://example.com/images/b2b-product.jpg', 0, 'user_007', '["tag3"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Mobile Product Strategy', 'Develop mobile-first product strategies. Learn mobile user behavior, app store dynamics, and mobile monetization.', 'https://example.com/images/mobile-product.jpg', 1, 'user_007', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Product Market Fit Validation', 'Achieve and measure product-market fit. Learn validation techniques, pivot strategies, and growth indicators.', 'https://example.com/images/pmf.jpg', 1, 'user_007', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Technical Debt in Product Management', 'Balance features with technical health. Learn technical debt assessment, communication, and prioritization strategies.', 'https://example.com/images/technical-debt.jpg', 0, 'user_007', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'International Product Expansion', 'Scale products globally. Learn localization, cultural adaptation, regulatory compliance, and international strategies.', 'https://example.com/images/global-product.jpg', 1, 'user_007', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Product Management Tools', 'Leverage PM tools effectively. Compare Jira, Asana, Notion, roadmap tools, and analytics platforms for product teams.', 'https://example.com/images/pm-tools.jpg', 1, 'user_007', '["tag2"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Career Growth in Product Management', 'Advance your PM career. Learn skill development, networking, portfolio building, and leadership progression paths.', 'https://example.com/images/pm-career.jpg', 0, 'user_007', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'AI Integration in Product Strategy', 'Incorporate AI into product offerings. Learn AI capabilities, implementation strategies, and ethical considerations.', 'https://example.com/images/ai-product.jpg', 1, 'user_007', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- Henry Chen's Blog Posts (user_008) - 20 posts
(gen_random_uuid(), 'Cybersecurity Fundamentals for Developers', 'Build security into applications from the start. Learn threat modeling, secure coding, and vulnerability prevention.', 'https://example.com/images/cyber-fundamentals.jpg', 1, 'user_008', '["tag1", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Web Application Security Testing', 'Test web apps for security vulnerabilities. Learn OWASP Top 10, penetration testing, and security scanning tools.', 'https://example.com/images/web-security-testing.jpg', 1, 'user_008', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Network Security Architecture', 'Design secure network infrastructures. Learn firewalls, VPNs, network segmentation, and intrusion detection systems.', 'https://example.com/images/network-security.jpg', 1, 'user_008', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Identity and Access Management', 'Implement robust IAM systems. Learn authentication, authorization, single sign-on, and identity governance strategies.', 'https://example.com/images/iam.jpg', 0, 'user_008', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '17 days', NOW() - INTERVAL '16 days', NULL),
(gen_random_uuid(), 'Cloud Security Best Practices', 'Secure cloud deployments effectively. Learn shared responsibility, configuration management, and cloud-native security.', 'https://example.com/images/cloud-sec.jpg', 1, 'user_008', '["tag1", "tag2", "tag3"]'::jsonb, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Incident Response Planning', 'Prepare for security incidents. Learn response procedures, forensics, containment strategies, and recovery processes.', 'https://example.com/images/incident-response.jpg', 1, 'user_008', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Encryption Implementation Guide', 'Protect data with encryption. Learn symmetric/asymmetric encryption, key management, and cryptographic best practices.', 'https://example.com/images/encryption.jpg', 0, 'user_008', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '14 days', NOW() - INTERVAL '13 days', NULL),
(gen_random_uuid(), 'Security Compliance Frameworks', 'Navigate compliance requirements. Learn SOC 2, ISO 27001, GDPR, HIPAA, and compliance implementation strategies.', 'https://example.com/images/compliance.jpg', 1, 'user_008', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'API Security Implementation', 'Secure APIs effectively. Learn authentication methods, rate limiting, input validation, and API security testing.', 'https://example.com/images/api-security.jpg', 1, 'user_008', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Security Monitoring and SIEM', 'Implement security monitoring. Learn SIEM systems, log analysis, threat detection, and security operations centers.', 'https://example.com/images/siem.jpg', 0, 'user_008', '["tag3"]'::jsonb, NOW() - INTERVAL '11 days', NOW() - INTERVAL '10 days', NULL),
(gen_random_uuid(), 'Mobile Application Security', 'Secure mobile apps comprehensively. Learn platform security models, secure storage, communication, and testing.', 'https://example.com/images/mobile-app-security.jpg', 1, 'user_008', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'DevSecOps Implementation', 'Integrate security into DevOps. Learn security automation, secure CI/CD, infrastructure security, and shift-left testing.', 'https://example.com/images/devsecops.jpg', 1, 'user_008', '["tag2", "tag3", "tag4"]'::jsonb, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Threat Intelligence and Analysis', 'Leverage threat intelligence effectively. Learn threat hunting, indicator analysis, and intelligence-driven security.', 'https://example.com/images/threat-intel.jpg', 0, 'user_008', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days', NULL),
(gen_random_uuid(), 'Zero Trust Security Model', 'Implement zero trust architecture. Learn trust verification, micro-segmentation, and continuous authentication strategies.', 'https://example.com/images/zero-trust-sec.jpg', 1, 'user_008', '["tag2", "tag3"]'::jsonb, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Container and Kubernetes Security', 'Secure containerized environments. Learn image security, runtime protection, network policies, and K8s security.', 'https://example.com/images/container-k8s-security.jpg', 1, 'user_008', '["tag1", "tag2", "tag4"]'::jsonb, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Security Awareness Training', 'Build security-conscious teams. Design training programs, phishing simulations, and security culture initiatives.', 'https://example.com/images/security-awareness.jpg', 0, 'user_008', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL),
(gen_random_uuid(), 'Vulnerability Management Program', 'Manage vulnerabilities systematically. Learn scanning, assessment, prioritization, and remediation workflows.', 'https://example.com/images/vuln-mgmt.jpg', 1, 'user_008', '["tag1", "tag3"]'::jsonb, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Security Risk Assessment', 'Assess and manage security risks. Learn risk frameworks, assessment methodologies, and risk treatment strategies.', 'https://example.com/images/risk-assessment.jpg', 1, 'user_008', '["tag2", "tag4"]'::jsonb, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Emerging Security Threats', 'Stay ahead of evolving threats. Analyze current threat landscape, emerging attack vectors, and defense strategies.', 'https://example.com/images/emerging-threats.jpg', 0, 'user_008', '["tag3", "tag4"]'::jsonb, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL),
(gen_random_uuid(), 'Future of Cybersecurity', 'Explore cybersecurity''s future. Discuss AI in security, quantum threats, IoT security, and next-generation defense.', 'https://example.com/images/cyber-future.jpg', 1, 'user_008', '["tag1", "tag4"]'::jsonb, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day');

-- Reset client messages
RESET client_min_messages;

-- Display comprehensive statistics
SELECT 
    '=== BLOG POST CREATION SUMMARY ===' AS "Report Section",
    '' AS "Details"

UNION ALL

SELECT 
    'Total Blog Posts Created:',
    COUNT(*)::text
FROM "BlogPosts"

UNION ALL

SELECT 
    'Published Posts:',
    COUNT(*)::text
FROM "BlogPosts"
WHERE "Status" = 1

UNION ALL

SELECT 
    'Draft Posts:',
    COUNT(*)::text
FROM "BlogPosts"
WHERE "Status" = 0

UNION ALL

SELECT 
    '=== POSTS PER AUTHOR ===' AS "Report Section",
    '' AS "Details";

-- Posts per author summary
SELECT 
    u."Name" AS "Author",
    COUNT(bp."Id")::text AS "Total Posts",
    COUNT(CASE WHEN bp."Status" = 1 THEN 1 END)::text AS "Published",
    COUNT(CASE WHEN bp."Status" = 0 THEN 1 END)::text AS "Drafts"
FROM "Users" u
LEFT JOIN "BlogPosts" bp ON u."Id" = bp."AuthorId"
GROUP BY u."Id", u."Name"
ORDER BY u."Name";

-- Tag usage statistics
SELECT 
    '=== TAG USAGE STATISTICS ===' AS "Section",
    '' AS "Tag",
    '' AS "Usage Count"

UNION ALL

SELECT 
    '' AS "Section",
    tag AS "Tag",
    COUNT(*)::text AS "Usage Count"
FROM "BlogPosts" bp,
     jsonb_array_elements_text(bp."Tags") AS tag
GROUP BY tag
ORDER BY COUNT(*) DESC;

-- Recent posts sample
SELECT 
    '=== RECENT BLOG POSTS SAMPLE ===' AS "Section",
    '' AS "Title",
    '' AS "Author",
    '' AS "Status",
    '' AS "Tags"

UNION ALL

SELECT 
    '' AS "Section",
    CASE 
        WHEN LENGTH(bp."Title") > 50 
        THEN LEFT(bp."Title", 47) || '...'
        ELSE bp."Title"
    END AS "Title",
    u."Name" AS "Author",
    CASE bp."Status"
        WHEN 0 THEN 'Draft'
        WHEN 1 THEN 'Published'
        WHEN 2 THEN 'Deleted'
    END AS "Status",
    bp."Tags"::text AS "Tags"
FROM "BlogPosts" bp
JOIN "Users" u ON bp."AuthorId" = u."Id"
ORDER BY bp."CreatedAt" DESC
LIMIT 10;

