version: "3.8"
services:
  postgres-blogs:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=PancakesBlogDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_blogs_data:/var/lib/postgresql/data

  postgres-users:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=PancakesUserDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  postgres-admin:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=PancakesAdminDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "${ADMIN_POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data
volumes:
  postgres_blogs_data:
  postgres_users_data:
  postgres_admin_data:
