version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_BLOG_API_URL=http://blogservice:80
    depends_on:
      - blogservice

  blogservice:
    build: ./backend/BlogService
    ports:
      - "5001:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file:
      - .env.compose
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: