version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  testmicroservice:
    build: ./backend/TestMicroservice
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development