name: Test and Coverage

on:
  push:
    branches: [ master, Master, dev, Dev ]
  pull_request:
    branches: [ master, Master, dev, Dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show test project files (debug)
        shell: bash
        run: |
          echo "Repo root: $(pwd)"
          ls -la
          echo "Listing AdminService.Tests directory contents"
          ls -la backend/AdminService.Tests || true
          echo "Listing TestUtilities directory contents"
          ls -la backend/AdminService.Tests/TestUtilities || true
          echo "List all .cs files under AdminService.Tests"
          find backend/AdminService.Tests -type f -name "*.cs" | sort

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            9.0.x
          cache: false

      - name: Restore (solutions or projects)
        shell: bash
        run: |
          set -euo pipefail
          echo "Searching for solution files..."
          mapfile -d '' SLNS < <(find . -type f -name "*.sln" -print0)
          if [ ${#SLNS[@]} -gt 0 ]; then
            for s in "${SLNS[@]}"; do
              echo "Restoring solution: $s"
              dotnet restore "$s"
            done
          else
            echo "No .sln files found. Restoring all .csproj files..."
            mapfile -d '' PROJS < <(find . -type f -name "*.csproj" -print0)
            if [ ${#PROJS[@]} -eq 0 ]; then
              echo "No .csproj files found. Nothing to restore."
              exit 1
            fi
            for p in "${PROJS[@]}"; do
              echo "Restoring project: $p"
              dotnet restore "$p"
            done
          fi

      - name: Dotnet info (diagnostics)
        run: dotnet --info

      - name: Build (Release)
        shell: bash
        run: |
          set -euo pipefail
          echo "Searching for solution files..."
          mapfile -d '' SLNS < <(find . -type f -name "*.sln" -print0)
          if [ ${#SLNS[@]} -gt 0 ]; then
            for s in "${SLNS[@]}"; do
              echo "Building solution: $s"
              dotnet build "$s" --configuration Release --no-restore
            done
          else
            echo "No .sln files found. Building all .csproj files..."
            mapfile -d '' PROJS < <(find . -type f -name "*.csproj" -print0)
            if [ ${#PROJS[@]} -eq 0 ]; then
              echo "No .csproj files found. Nothing to build."
              exit 1
            fi
            for p in "${PROJS[@]}"; do
              echo "Building project: $p"
              dotnet build "$p" --configuration Release --no-restore
            done
          fi

      - name: Test all *\.Tests projects with coverage
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifacts/test-results
          # Find and test all projects ending with .Tests.csproj
          mapfile -d '' TEST_PROJECTS < <(find . -type f -name "*.Tests.csproj" -print0)
          if [ ${#TEST_PROJECTS[@]} -eq 0 ]; then
            echo "No *.Tests.csproj projects found. Searching for test DLLs as fallback..."
            # Fallback: run dotnet test on solutions if any
            mapfile -d '' SLNS < <(find . -type f -name "*.sln" -print0)
            if [ ${#SLNS[@]} -gt 0 ]; then
              for s in "${SLNS[@]}"; do
                echo "Running tests for solution: $s"
                OUTDIR="artifacts/test-results/$(dirname "$s" | sed 's#^./##;s#/#_#g')"
                mkdir -p "$OUTDIR"
                dotnet test "$s" \
                  --configuration Release \
                  --no-build \
                  --collect:"XPlat Code Coverage" \
                  --results-directory "$OUTDIR"
              done
              exit 0
            fi
            echo "No tests discovered. Failing."
            exit 1
          fi
          for proj in "${TEST_PROJECTS[@]}"; do
            echo "Running tests for: $proj"
            OUTDIR="artifacts/test-results/$(dirname "$proj" | sed 's#^./##;s#/#_#g')"
            mkdir -p "$OUTDIR"
            dotnet test "$proj" \
              --configuration Release \
              --no-build \
              --collect:"XPlat Code Coverage" \
              --results-directory "$OUTDIR"
          done

      - name: Install ReportGenerator
        shell: bash
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate coverage report (HTML + TextSummary)
        shell: bash
        env:
          REPORT_DIR: artifacts/coverage
        run: |
          mkdir -p "$REPORT_DIR"
          reportgenerator \
            -reports:"artifacts/test-results/**/coverage.cobertura.xml" \
            -targetdir:"$REPORT_DIR" \
            -reporttypes:"Html;TextSummary"
          echo "---- Text Summary ----"
          cat "$REPORT_DIR/Summary.txt" || true

      - name: Enforce coverage thresholds (Line >= 70%, Branch >= 50%)
        shell: bash
        env:
          REPORT_DIR: artifacts/coverage
          MIN_LINE: "70"
          MIN_BRANCH: "50"
        run: |
          set -euo pipefail
          SUMMARY_FILE="$REPORT_DIR/Summary.txt"
          if [ ! -f "$SUMMARY_FILE" ]; then
            echo "Coverage summary not found at $SUMMARY_FILE"
            exit 1
          fi
          LINE=$(grep -Po 'Line coverage:\s*\K[0-9.]+(?=%)' "$SUMMARY_FILE" || echo "0")
          BRANCH=$(grep -Po 'Branch coverage:\s*\K[0-9.]+(?=%)' "$SUMMARY_FILE" || echo "0")
          echo "Line: ${LINE}%  Branch: ${BRANCH}%"
          FAIL=""
          awk -v a="$LINE" -v b="$MIN_LINE" 'BEGIN{ if (a+0 < b+0) exit 1 }' || FAIL="line"
          awk -v a="$BRANCH" -v b="$MIN_BRANCH" 'BEGIN{ if (a+0 < b+0) exit 1 }' || FAIL="$FAIL branch"
          if [ -n "$FAIL" ]; then
            echo "Coverage below thresholds ($FAIL). Required: Line >= ${MIN_LINE}%, Branch >= ${MIN_BRANCH}%"
            exit 1
          fi
          echo "Coverage meets thresholds."

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: artifacts/coverage
          if-no-files-found: error


